pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/MikaGronroos2/OHTP1.git', branch: 'main', credentialsId: '88639197-96eb-4b56-a471-8ecd32f99bd9'
            }
        }

        stage('Build') {
            steps {
                dir('Week5_lectureAssignment') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Week5_lectureAssignment') {
                    bat 'mvn test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('Week5_lectureAssignment') {
                    jacoco execPattern: '**/target/jacoco.exec'
                }
            }
        }
    }

    post {
        always {
            dir('Week5_lectureAssignment') {
                junit '**/target/surefire-reports/*.xml'
                jacoco execPattern: '**/target/jacoco.exec'
            }
        }
    }
}
