pipeline {
    agent any

    environment {
        // Define Docker Hub credentials ID
        DOCKERHUB_CREDENTIALS_ID = 'docker-hub-token'  // Change this to match your Jenkins credentials ID
        // Define Docker Hub repository name
        DOCKERHUB_REPO = 'mikagro/dockerhub'
        // Define Docker image tag
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/MikaGronroos2/OHTP1.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('W6_Homework') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }
        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    withDockerRegistry([ credentialsId: "${DOCKERHUB_CREDENTIALS_ID}", url: 'https://index.docker.io/v1/' ]) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push("${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }
    }
}
